package com.joxad.easydatabinding.activity;

import android.content.Intent;
import android.databinding.DataBindingUtil;
import android.databinding.ViewDataBinding;
import android.os.Bundle;
import android.support.annotation.LayoutRes;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;

/**
 * {@link ActivityBase} will allow you to generate a basic activity that put your view model {@link B} and its {@link VM}
 */
public abstract class ActivityBase<B extends ViewDataBinding, VM extends ActivityBaseVM> extends AppCompatActivity {

    /***
     * Binding activity class generated by Android
     */
    protected B binding;
    /***
     * Your VM class
     */
    protected VM vm;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = DataBindingUtil.setContentView(this, layoutResources());
        binding.setVariable(data(), baseActivityVM(binding));
    }

    public abstract int data();

    @LayoutRes
    public abstract int layoutResources();

    public abstract VM baseActivityVM(B binding);


    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (vm instanceof IActivityVM)
            ((IActivityVM) vm).onActivityResult(requestCode, resultCode, data);
    }

    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        if (vm instanceof IActivityVM)
            ((IActivityVM) vm).onNewIntent(intent);
    }
}
