package com.joxad.easydatabinding.fragment;

import android.databinding.DataBindingUtil;
import android.databinding.ViewDataBinding;
import android.os.Bundle;
import android.support.annotation.LayoutRes;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

/**
 * Created by josh on 13/04/16.
 */
public abstract class FragmentBase<B extends ViewDataBinding, VM extends FragmentBaseVM> extends Fragment {

    /***
     * FragmentBinding used in this view
     */
    protected B binding;
    /***
     * The view model that will be used to handle this fragment
     */
    protected VM vm;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, layoutResources(), container, false);
        binding.setVariable(data(), baseFragmentVM(binding));
        return binding.getRoot();
    }

    /**
     * The int value found in the {@link com.joxad.easydatabinding.BR} class generated by DataBinding
     *
     * @return
     */
    public abstract int data();

    /***
     * @return your layout resources
     */
    @LayoutRes
    public abstract int layoutResources();

    /***
     * @param binding
     * @return the {@link VM} you want to use in this activity
     */
    public abstract VM baseFragmentVM(B binding);
}
